### ISSUE TITLE
Ensure BitBucket (Cloud) Support

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1047]
# Summary
- [x] solve #188
- [x] update apis ...
- [ ] use https://github.com/ktrysmt/go-bitbucket ?

**Comment by MartinHerren** [comment]
Hej,

had time to try to investigate bitbucket cloud a little more. Managed to build my own Woodpecker server so i could add some logging to identify where it fails (i'm not fluent in go but it is on my roadmap to learn it).

The current behavior i have:
I can connect Woodpecker to bitbucket and log in. No error visible on woodpecker's UI. But i cannot get a list of repositories.

Checks through cli:
❯ go run ./cmd/cli info
12:59PM ??? cli/common/zerologger.go:18 > LogLevel = debug
User: xxxxx
Email: 
❯ go run ./cmd/cli user info
12:59PM ??? cli/common/zerologger.go:18 > LogLevel = debug
12:59PM FTL cmd/cli/main.go:27 > error running cli error="Missing or invalid user login"
exit status 1

It seems i'm basically logged in but it can not retrieve my user info. Also i cannot get a repository list: It fails when accessing the https://api.bitbucket.org/2.0/teams/?pagelen=100&role=member endpoint.

So it seems that what's currently broken in bitbucket is most or all related to some apis that have been deprecated and removed last year: https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/

I don't know how i can help more on the issue for now. The best solution is probably to go through the go-bitbucket module instead of re-implementing the whole api.

**Comment by MartinHerren** [comment]
Have a first hack to be able to retrieve the list of repositories of al workspaces a user has access:
https://github.com/woodpecker-ci/woodpecker/compare/master...MartinHerren:woodpecker:bitbucket_get_repo_fix

Still need to cleanup the commit and align the tests to pass again.

User info/email still doesn't work but i managed to run my first 'hello world pipeline' with Woodpecker connected to bitbucket cloud.

**Comment by 6543** [comment]
@MartinHerren if you like just open a pull and allow maintainers to edit stuff, so we can help out ;)

**Comment by MartinHerren** [comment]
Yes, just a last cleanup and a rebase and i'll open a PR asap

**Comment by MartinHerren** [comment]
Rebased to master and opened a WIP PR. Still need to align the tests. But already managed to run successfully a simple 'hello world' pipeline connected to bitbucket.org. User management still needs fixing (like retrieving user email for example).

**Comment by 6543** [comment]
It would be nice If somebody could profide up to date webhook examples for:
 - tagging
 - pull-request creating/updating/closing/merging

to update https://github.com/woodpecker-ci/woodpecker/blob/master/server/remote/bitbucket/fixtures/hooks.go

**Comment by MartinHerren** [comment]
> It would be nice If somebody could provide up to date webhook examples for:
> 
>     * tagging
> 
>     * pull-request creating/updating/closing/merging
> 
> 
> to update https://github.com/woodpecker-ci/woodpecker/blob/master/server/remote/bitbucket/fixtures/hooks.go

Will take care of that.

Haven't seen a trigger for 'Tagging', there is only one for 'Repository Updated'. To test if it triggers on tag.

For Pull requests, there are triggers among others for
- Created
- Updated
- Merged
- Declined (might match the 'closing' need) ?

**Comment by segux** [comment]
Hi, are you working on this one? Thanks
