### ISSUE TITLE
Superseded builds - Skip outdated builds

### ISSUE THREAD

**Issue by laszlocph** [woodpecker-ci/woodpecker#11]
If a new commit arrives to a branch, cancel the older build.

Today with quickly repeated commits and pushes, the CI builds for all commits. The goal would be to cancel the build running on the older commit, since it's not relevant anymore, just holds up resources.

**Comment by laszlocph** [comment]
https://discourse.drone.io/t/feature-build-auto-cancel/401

**Comment by 6543** [comment]
I'm not sure if this should be enforced by server or be a repo config or in yaml ...

what do you think is best?

**Comment by 6543** [comment]
-> config option for repos, that could be enforced/overwritten by the server

**Comment by anbraten** [comment]
Let start with config option you can set per repo in the settiings.
We probably need multiple options:
- Skip Push? Will probably be inactive as we wont to make sure every push to the default branch gets tested and path changes could skip some tests completly
- Skip pull requests: This is probably the most important option

In addition we should think about already running pipelines. Should there be a way to skip them? Gitlab for example allows to set `interrupt: true` on step level as we normally need previous steps because of wps workspace feature we could think about adding such an interrupt option per pipeline config.
