### ISSUE TITLE
repo list allow to open in new tab

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1259]
repo list should also be as able as build list to open in a new tab

**Comment by CypherpunkSamurai** [comment]
Hello @6543,

I would like to contribute to this issue. How can i get started? :)

**Comment by 6543** [comment]
@CypherpunkSamurai 👋 

https://woodpecker-ci.org/docs/next/development/ui 

all the `next` docu about development is interesting in this case ... but especialy the UI part

**Comment by hay-kot** [comment]
> Could you please clarify the issue? 

The element that is the link is rendered as a `button` element and not a `a` element. This is incorrect HTML semantics and reduces accessibility. You can still use middle click because it still triggers the on-click action and programmatically navigates to the page. 

This PR fixes the issue though

- https://github.com/woodpecker-ci/woodpecker/pull/1602

**Comment by janydoe** [comment]
> The element that is the link is rendered as a `button` element and not a `a` element.

I agree if you are talking about an add repository button, for example. If this list of repositories is what @6543  meant, thank you for clarifying the task)
