### ISSUE TITLE
Configuration with pure GIT

### ISSUE THREAD

**Issue by Spaceman2019** [woodpecker-ci/woodpecker#1481]
Hi,
I am currently evaluating CI's, I have a question: how do I configure the server for a connection to a pure Git server (no GitHub, GitLab ...)
Thanks for the information

**Comment by anbraten** [comment]
That's not possible atm, but could maybe be supported. Question to answer:
- How will Woodpecker know that you have done a git operation (push, tag, etc). Those events are currently send as webhooks from the configured forge
- How do you login to Woodpecker? Woodpecker is using oauth or similar concepts atm to allow users to login with their account from the configured forge

Could you explain why considered using  pure git instead of something like Gitea (still pretty lightweight) and how do you plan on using a CI?

**Comment by TechnologyClassroom** [comment]
[Git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) could notify Woodpecker of a change.
