### ISSUE TITLE
Add Kubernetes runner

### ISSUE THREAD

**Issue by laurivosandi** [woodpecker-ci/woodpecker#1492]
### Clear and concise description of the problem

We run Kubernetes-only infra and we run all the workers in Kuberentes clustes cluster. The piece that enables using Drone on Kubernetes is https://github.com/drone-runners/drone-runner-kube/ however that is not released under (OSI approved) open source license.

Somewhat related to #1491

### Suggested solution

Please provide alternative clean room implementation that at least works with Woodpecker CI.

### Alternative

Yes we could have runners in classic VM-s but I really want to avoid maintaining any more classic VM-s

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by gapodo** [comment]
Using kubernetes is already possible in the next version (agent backed kubernetes), and works ok, it has potential for improvement (resource quotas when running steps ok k8s native).

Also running the "normal" woodpecker-agent as a self contained builder (think dink instead of dind) is also possible (even with 0.15)
