### ISSUE TITLE
Github repository list empty

### ISSUE THREAD

**Issue by dessalines** [woodpecker-ci/woodpecker#1582]
### Component

server

### Describe the bug

I'm trying to set up woodpecker. I finally got oauth working, and logged in with my personal user.

The repo list shows as empty.

I click `Add Repository`, then `Reload repositories`, and after 10 seconds, it says `Repository list loaded`... yet the list is still empty.

I've tried changing many of the vars below, all with no luck. 

The oauth is most likely working fine, so I don't know why it can't load my repo list.

```
environment:
  - WOODPECKER_OPEN=true
  - WOODPECKER_HOST=https://drone.join-lemmy.org
  - WOODPECKER_LOG_LEVEL=info
  - WOODPECKER_AGENT_SECRET=${DRONE_RPC_SECRET}
  - WOODPECKER_GITHUB=true
  - WOODPECKER_GITHUB_CLIENT=${CLIENT_ID}
  - WOODPECKER_GITHUB_SECRET=${SECRET}
  - WOODPECKER_ADMIN=dessalines
  - WOODPECKER_REPO_OWNERS=dessalines
```

### System Info

```shell
`{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.6"}`
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by dessalines** [comment]
I did a completely from-scratch install, with a new domain, and new oauth, and I can confirm this is an issue.

**Comment by dessalines** [comment]
Any updates on this? We'd really like to switch from drone to woodpecker for Lemmy, but this is a blocker.

**Comment by 6543** [comment]
hmm it could be that github do limit the api requests ...

**Comment by 6543** [comment]
@dessalines you could try `WOODPECKER_FLAT_PERMISSIONS=true`

read more at  #625

**Comment by dessalines** [comment]
Tried both that, and flat, still empty.

It has a green popup that says repository list empty, and the logs contain nothing.

**Comment by dessalines** [comment]
Any other possible solutions? We'd really like to switch to woodpecker for lemmy.

**Comment by dessalines** [comment]
@anbraten 

Broken on both `0.15.6` and `next`.

It says "Repository list loaded" in a green toast, yet nothing is loaded. Nothing in the logs.

**Comment by anticitizn** [comment]
Same results here, neither `0.15.6` nor `next` can load the list of repos on a seemingly correctly configured installation

**Comment by hay-kot** [comment]
I'm also having the same issue. It's easily replicated in development by creating a new token w/ a new database. The Sync repositories all works fine with the `WOODPECKER_FLAT_PERMISSIONS=true` workaround and everything is saved in the database. However, no results are returned via the API because of this query

https://github.com/hay-kot/woodpecker/blob/15a50bc0a3ca7346e96a46948c2122bd8b2f9a36/server/store/datastore/repo.go#L148-L150

```go
if owned {
    sess = sess.And(builder.Eq{"perms.perm_push": true}.Or(builder.Eq{"perms.perm_admin": true}))
}
```

If you use the work around `per_push` and `perm_admin` are both always false

Pretty sure it's just a logical issue here:

https://github.com/hay-kot/woodpecker/blob/15a50bc0a3ca7346e96a46948c2122bd8b2f9a36/server/forge/userSyncer.go#L81

`repo.Perm` will never be null because it's assigned directly above. 

This PR will fix the issue, but I'm not sure if that's the expected behavior? 

- https://github.com/woodpecker-ci/woodpecker/pull/1603

**Comment by dessalines** [comment]
It worked on `next`, thanks!

**Comment by 6543** [comment]
finally :tada:

**Comment by bergpb** [comment]
Using `next` version I was able to list all repositories, but when I click in Enable, only shows a unauthorized error in network.
