### ISSUE TITLE
[Docs] Hardware requirements

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#1742]
### Clear and concise description of the problem

Most CI/CD products' documentation have a small "hardware requirements" section. Please consider adding one for Woodpecker.

Knowing what kind of cpu/memory is required for running the app is important when commissioning a server.

I was especially interested in woodpecker because it's written in go, and should be (?) much faster and lighter than something like jenkins. But still, one needs some basic idea what sort of hardware to use.

### Suggested solution

A small section "Hardware Requirements" in the [administration - setup](https://woodpecker-ci.org/docs/next/administration/setup) docs.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
Interesting point. To summarize it: Woodpecker needs a few components:
- a server running a probably pretty lightweight go app (and web ui)
- a database server like postgres / mysql or sqlite using almost not resources
- a set of agents (those need almost no resources in idle, and otherwise the resources your pipeline tasks require)

Could you add those parts to the docs?
