### ISSUE TITLE
Drop Bitbucket Server support

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1962]
We currently have support for Bitbucket cloud and bitbucket server (formerly stash). As bitbucket server will no longer be supported starting Febuary 15, 2024 and is only partly supported / implemented by Woodpecker we should drop support.

![image](https://github.com/woodpecker-ci/woodpecker/assets/6918444/acaedf6a-ccb9-4ec5-809b-e9fa64f6542c)

**Comment by anbraten** [comment]
Would fit into it. Just wanted to check if someone is against removing it first.

**Comment by majodev** [comment]
It's kind of a bummer that support was removed, as [Bitbucket Data Center](https://www.atlassian.com/de/software/bitbucket/enterprise/data-center) (the on-premise license that is supported by Atlassian going forward) actually worked fine with the pre v1 versions.

We are still actively using v0.14.3 with Bitbucket Data Center (a quite recent v8.8.2) and tried to migrate to `next/v1` earlier this year (with https://github.com/woodpecker-ci/woodpecker/issues/1695 being the only blocker).

**Comment by 6543** [comment]
@majodev we can re-add it, but we will need your support to test it and provude us example data to write up to date fixtures for unit tests

**Comment by majodev** [comment]
@6543 sure, could support regarding testing.

* Could you provide a specific docker image tag with support reenabled? Otherwise AFAIK I could only test [v0.15.11](https://github.com/woodpecker-ci/woodpecker/releases/tag/v0.15.11).
* Any special format requirements regarding example data / fixtures (similar to https://github.com/woodpecker-ci/woodpecker/issues/1695 OK?)

**Comment by 6543** [comment]
To discusst this future can you open a new issue and link to this one please?
