### ISSUE TITLE
invisible pipeline ".drone.yaml" if ".drone" multi pipeline is used

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#239]
if you use a folder to store pipelines in it, and call one of them `.drone.yaml` it wont show up in ui

**Comment by ygbillet** [comment]
I investigate a bit this issue.

It seems to come from [web/src/screens/repo/screens/build/components/procs.js](https://github.com/woodpecker-ci/woodpecker/blob/c699ea5789c136903a72aee935de5f51f6728c82/web/src/screens/repo/screens/build/components/procs.js#L36).

I'm not so fluent in JavaScript, so i'm not sure how to proceed.

**Comment by ygbillet** [comment]
How it works today :  if the name of "proc" (see JSON in browser) is drone, we assume we are not in multipipeline mode.

Two options : 

- Instead of checking names, we could check if there are multiple procs or only one. But i don't know how to do that (i never learn React).
- Maybe we shouldn't change anything and write in the doc not to use ".drone.yml" or "drone.yml" as the name of the file. The rationale behind it : name of a file describes a "pipeline". A pipeline "drone" is not very explicit, better use : tests, lint, build, publish, docker, doc, etc.

**Comment by 6543** [comment]
@anbraten this one;)
