### ISSUE TITLE
Replace `NetrcOnlyTrusted` with list of trusted plugins for netrc

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#2601]
As noticed in several PRs the current option `NetrcOnlyTrusted` is limiting users, but on the other hand not really protecting them as well as netrc credentials could be stolen by a custom clone step with custom commands. 

- https://github.com/woodpecker-ci/woodpecker/pull/2585#issuecomment-1765756023
- https://github.com/woodpecker-ci/woodpecker/pull/2214

To prevent this a `pass-netrc-to-plugins` option should replace the `NetrcOnlyTrusted` option. This option would contain list of images which will receive the netrc credentials if they are used as plugins. If the image however uses custom commands it wont get the credentials as those commands could be changed by others than the admin.

This will allow all steps and the clone step to use netrc credentials. It will however be breaking as it wont be possible anymore to use clone steps with custom commands.

**Comment by pat-s** [comment]
>  If the image however uses custom commands it wont get the credentials

Then we're still missing an option that allows the use of credentials in custom steps/images. If the repo admin wants to allow it (e.g. in private repos).
Currently this is only possible on the instance level by setting the repo to "trusted" but not on the repo level.

So why not structure it like this:

1. Option to allow injecting netrc into plugins/trusted images
2. Option to allow injecting netrc into any image

The use case I had was a step executing arbitrary git commands, among them `git push`, to push back to the repo. Many people like this style instead of having to use a plugin as it "feels like freedom" ;)

**Comment by 6543** [comment]
is this not solved by simply make

https://github.com/woodpecker-ci/woodpecker/blob/26b77ed677bb6121f35cdba2731692d26bd5b3de/shared/constant/constant.go#L39-L42

as an configuration option?

**Comment by 6543** [comment]
an option only instance admins should change in any case

**Comment by 6543** [comment]
well that would allow any one to steal other users credentials at codeberg:
1. propose for ci acces
2. create own repo
3. let other users creat pulls
4. you got all there oauth2 tokens :tada:

**Comment by anbraten** [comment]
> you got all there oauth2 tokens 🎉

I am also not for exposing those secrets to easily (as commented before), but your point seems to be wrong.

> Is cloning using the tokens of the pipeline authors? Shouldn't it use the repo users/owners?

It uses the oauth token of the first repo admin (might be updated to another repo admin later not 100% sure).

>  Maybe we should limit this to plugins?

An image filter would be for plugins only as otherwise it would not limit protect (similar to #2213).

**Comment by runephilosof-karnovgroup** [comment]
For github forge, it would make the credentials non-sensitive, if it is converted to a github app, using short lived and restricted access tokens.
Is something similar possible on the other forges?

**Comment by pat-s** [comment]
Do we know how other CI providers handle this? We should also take into account that this is a complicated situation for users if "too much" magic is happening behind the scenes or certain things only apply in some special situations. Also WRT to documentation.

A situation which is popular in the instances I managed (and which worked/still works in drone) is to use arbitrary git commands to apply some git modifications and then push back to the cloned repo. For this a git plugin would only partially help (unless it has a setting where one could input arbitrary git commands of infinite length).

**Comment by pat-s** [comment]
> How does drone handle this? It's a really critical security issue if you just expose some random oauth tokens.
Also, we can't say to just use the token of the pipeline author (e.g. PR author), because the pipeline author is not necessarily registered so we don't have a token.

I agree, not saying we should do the same. Just reporting how it works.
What I got as a reply from users when telling them to migrate their workflows was "Ugh, I don't like this, this is a step backwards. Can we stay with drone?" 🥴️ -> which is why I opened the discussion in the first place as I want them to use/be happy with WP of course 😅

**Comment by pat-s** [comment]
It's also not clear to me, unfortunately. The pipeline I am talking about does the following

```yml
kind: pipeline
type: kubernetes
name: CI

steps:
  - name: CI
    image: <some image with git>
    commands:
      - git fetch origin json
      [...]
      - git status
      - git diff --numstat
      - git remote -v
      - git add .
      - git commit --message "Automated import"
      - git push
```

and the `git push` just works. No manual secret added. I've checked the drone config itself and everything around (set up by myself) but I couldn't yet infer why this actually works. I know there is https://github.com/appleboy/drone-git-push for such use cases as it shouldn't work OOB. Maybe it's related to the drone kube runner which handles auth things differently compared to running drone on a single VM with the docker backend?

**Comment by anbraten** [comment]
> https://docs.drone.io/runner/docker/configuration/reference/drone-netrc-clone-only/

I am not 100% sure, but I think it is mounting [`/root/.netrc` to steps](https://github.com/harness/gitness/issues/2188#issuecomment-326319718).
