### ISSUE TITLE
wrap pipeline-config-lint error to tell the user it's one

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#460]
linter do cause error, that get back propagated without creating a status #459, but what's worse is, the error do not refer to a invalid pipeline config, we should wrap errors at some point to tell it's an wrong pipeline config

```
pipeline/frontend/yaml/linter/linter.go
70:		return fmt.Errorf("Invalid or missing image")
```
![Bildschirmfoto zu 2021-10-19 02-03-20](https://user-images.githubusercontent.com/24977596/137822474-cb41b1ff-f11c-43d7-a3bf-ec95d6e6a620.png)

**Comment by s-weigand** [comment]
Not sure if this belongs here or should be a stand-alone bug issue. 
Today I tried out woodpecker-ci (version: `0.15.0-rc2`) with a pipeline from drone-ci `2.7.3`

```yaml
kind: pipeline
type: docker
name: hello-world

steps:
  - name: say-hello
    image: busybox
    commands:
      - echo hello-world
```
Which generated the error `Invalid or missing pipeline section` in the UI.

My naive approach was to simply change `steps` to `pipeline` and then nothing happened, no errors and nothing in the server log.

After I switched the server to use debug mode (`WOODPECKER_LOG_LEVEL=debug`) I found this error.

```json
{
  "level": "debug",
  "error": "yaml: unmarshal errors:\n  line 6: cannot unmarshal !!seq into map[string]yaml.Container",
  "repo": "test-orga/test-repo",
  "time": "2022-02-19T17:50:54Z",
  "caller": "/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/hook.go:192",
  "message": "failure to parse yaml from hook"
}
```

I think that the linter should catch this before an actual parsing error occurs and that the log level should be `error`/`warn` instead of `debug`.
Also since most users won't have access to the server config and logs, yaml parsing error should be shown in the UI (just in case the linter doesn't get them first).

PS: Thanks for the awesome project ❤
