### ISSUE TITLE
Gitlab status / pipelines are separated

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#618]
Gitlab seems to have an issue which results in single Woodpecker pipelines being shown as multiple pipelines in Gitlab.

 expected:
![Screenshot from 2021-12-18 23-32-52](https://user-images.githubusercontent.com/6918444/146657586-ef8b3480-ab6b-4e0a-ac84-a10e73c3568d.png)

currently (two pipelines with a single job):
![Screenshot from 2021-12-18 23-33-12](https://user-images.githubusercontent.com/6918444/146657585-6687774a-4bf1-453d-a989-df58883ebfba.png)

Gitlab issue: https://gitlab.com/gitlab-org/gitlab/-/issues/13134

**Comment by dsanader** [comment]
Hello,

I've been hit by a similar issue where pipelines are duplicated in GitLab on push events. On merges it's even worth, since /push, /pr, /deployment are duplicated.

Gitlab's commit API is not used as it should it seems. Woodpecker [pushes an internal build ID](https://github.com/woodpecker-ci/woodpecker/blob/ecc25395aae1a536df2b32fa51e223538fcf5186/server/remote/gitlab/gitlab.go#L361) where GitLab [expects a GitLab pipeline ID](https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit) :

```golang
_, _, err = client.Commits.SetCommitStatus(_repo.ID, build.Commit, &gitlab.SetCommitStatusOptions{
	State:       getStatus(proc.State),
	Description: gitlab.String(common.GetBuildStatusDescription(proc.State)),
	TargetURL:   gitlab.String(common.GetBuildStatusLink(repo, build, proc)),
	Context:     gitlab.String(common.GetBuildStatusContext(repo, build, proc)),
	PipelineID:  gitlab.Int(int(build.Number)),
}, gitlab.WithContext(ctx))
```

This is more obvious in posted requests bodies (pipeline_ids displayed in my project are at 35xxx) :

```json
{
  "state": "pending",
  "context": "ci/woodpecker/push/woodpecker",
  "target_url": "https://wp.example.com/org/dummy/build/6/1",
  "description": "Pipeline is pending",
  "pipeline_id": 6
}
{
  "state": "success",
  "context": "ci/woodpecker/push/woodpecker",
  "target_url": "https://wp.example.com/org/dummy/build/6/1",
  "description": "Pipeline was successful",
  "pipeline_id": 6
}
```
Since pipeline_id is not mandatory, I'll try running my server without it for a few days and report back. It already seems OK for push events.

For the multi-pipeline feature, I guess I means we should looking up pipeline_ids to find which one to post the updated status to.

**Comment by dsanader** [comment]
Proposed a PR since I've been running this successfully for a while now.
