### ISSUE TITLE
monitor if docker/go base image do have CVEs assigned and rebuild if so

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#644]
only affect
-> our alpine images
-> if there is issue with the go std lib so we have to recompile stuff

**Comment by pat-s** [comment]
Hmm, will we ever do this in an automated way? We build images so often and release so frequently. Monitoring all base images and taking instant action sounds a bit "over the top" for me, especially since `renovate` updates the deps on a weekly basis, we're pretty fast to pull sec updates in?

Given the size and scope of this project, I'd argue we're good and doing already quite a lot to keep everything fresh.

**Comment by anbraten** [comment]
Yes, renovate solves this somehow
